"""licence image truen

Revision ID: 307e3fba8d51
Revises: 39feb6bed4e3
Create Date: 2024-05-16 17:51:59.613776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307e3fba8d51'
down_revision = '39feb6bed4e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index('national_Id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index('national_Id', ['national_Id'], unique=True)

    # ### end Alembic commands ###
