"""Add licence_image_mime column to Customer

Revision ID: 41ae038ebe7c
Revises: 4bc4aec33021
Create Date: 2024-05-17 10:19:59.706258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41ae038ebe7c'
down_revision = '4bc4aec33021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('licence_image_mime', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('licence_image_mime')

    # ### end Alembic commands ###
