"""empty message

Revision ID: 4bc4aec33021
Revises: 81c61471d475
Create Date: 2024-05-16 22:04:01.909211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bc4aec33021'
down_revision = '81c61471d475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index('national_Id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index('national_Id', ['national_Id'], unique=True)

    # ### end Alembic commands ###
